### ISSUE TITLE
Multiple field validation

### ISSUE THREAD

**Issue by sagikazarmark** [fuelphp/validation#34]
Think about a case where the same field can have multiple values. For example a multiple select or any dynamically added form elements.

In this case the given data is an array of expected data which will probably make all rules failed (except required).

Since this is a problem at field level checking it in `Validator` (whether `Field->isMultiple()` is `true`) could be the solution. If it is rules should be run on all the input data.

**Comment by stevewest** [comment]
Closed with https://github.com/fuelphp/validation/commit/12b9a9a4bf9dd9c9af6c4a2e182c61051f4c5b16
