### ISSUE TITLE
Rule/Required.php will always return false.

### ISSUE THREAD

**Issue by mikepmtl** [fuelphp/validation#42]
Currently it is returning the following:
return ($value === false or $value === null or $value === '' or $value === array());
The ! empty($value) was removed which was giving the "true" value before.
And null and empty $value would now return true as well.

**Comment by stevewest** [comment]
I honestly don't know why the code was changed now but the original commit that caused this issue stated that it was a fix to allow `0` to be valid when the rule is required. The commit has been reverted in https://github.com/fuelphp/validation/commit/eb2db3917bf704216ea7525924a12df764d8f364

**Comment by WanWizard** [comment]
Just to check: so now zero is no longer valid? 

If so, this is something I don't agree with. "Required" is defined as "present and has a value", and zero meets both criteria. You could say than depending on contact `""` and `false` are also values.

**Comment by stevewest** [comment]
`0` is now valid, and so is `''` and `false`

**Comment by sagikazarmark** [comment]
@stevewest we discussed it earlier on IRC, I just don't remember the reasons. There were some WTF reasons we had to do this. (something like empty array, but not sure). I agree with @WanWizard here: we basically want to test if a specific reference has been set with ANY value.

**Comment by stevewest** [comment]
I vaguely remember that, next time I'll be sure to get one of us to open an issue with the information so this does not happen again. After reverting the commit and having a play with the rule it seems to be working as I would expect. `0` is valid `''` is valid, `[]` is valid, etc
