### ISSUE TITLE
Unique

### ISSUE THREAD

**Issue by eckoe** [fuelphp/validation#43]
How to use validation with database, like unique fields ?

**Comment by stevewest** [comment]
Please can you elaborate on your question? This validation package is not directly related to anything to do with databases, it's for validating arrays of data.

**Comment by sagikazarmark** [comment]
I guess you want something like "how to make sure that a username is unique before registration?".

You can create a rule for that. Check the current ones to see how to implement one.

**Comment by eckoe** [comment]
Sorry for my negligence, I know it´s a validation arrays of data. But like sagikazarmak said. I want to know how to check if data is unique before registration. I have checked the samples, but how to implement database driver to validation ? What´s the best way to do that ? Any idea ?

**Comment by stevewest** [comment]
As @sagikazarmark said you can write a custom rule and add that to your `Validator` there are instructions on how to do this in the readme https://github.com/fuelphp/validation#manually-adding-rules-and-rule-overriding

**Comment by stevewest** [comment]
@eckoe Did this help? If so the issue can be closed.
